on: push
jobs:
  build-esp32dev:
    name: Build binary for esp32 - dev board version 1
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Setup PlatformIO
        uses: n-vr/setup-platformio-action@v1
        with:
          platformio-version: "6.1.4"
      - name: Build PlatformIO project
        run: pio run -d ./ -e esp32dev
      - name: Adjust firmware filename
        run: mv .pio/build/nodemcuv2/firmware.bin firmware-esp32dev.bin
      - name: Release
        uses: fnkr/github-action-ghr@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GHR_PATH: firmware-esp32dev.bin
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
